--[[
AUTO-GENERATED - regenerated by scripts/luaDoc_generateStr.py
"////// GENERATED FROM <source>" regions are overwritten on each release
edit only "////// Manual entries and overrides" region at the bottom

This file can be used in your IDE or language server to enable autocomplete and Intellisense functionality.

Do not load it in the AddOn manifest file. Instead add it as an external or additional library in your IDE.

This file contains FurnitureCatalogue specific components that the IDE is not smart enough to know by itself.

This includes:
- global localisation strings that are defined locally
- definitions extracted from XMLs (currently none)

It should not include:
- undocumented or overwritten functions
- try to use documentation instead
- try to avoid overwriting existing functions
- ESO globals
- use a mix of Baertrams generated ESOAPI files and your own custom files instead
- see https://github.com/Baertram/IntelliJ_ESOUI_AutoCompletion
--]]
--

-- ////// START   : Manual entries and overrides

-- ESOAPI

---Get localised quest name by id
---@param questId integer
---@return string name or empty string
function GetQuestName(questId)
  return ""
end

--- @param currencyType number
--- @param isSingular bool|nil
--- @param isLower bool|nil
--- @return string name
function GetCurrencyName(currencyType, isSingular, isLower)
  return ""
end

--- @param unitTag string
--- @return string name
function GetUnitName(unitTag)
  return ""
end

---@class LinkStyle : number
LinkStyle = nil

--- @param achievementId integer
--- @param linkStyle LinkStyle
--- @return string link
function GetAchievementLink(achievementId, linkStyle)
  return ""
end

--[[ NUMBER FORMATTING

Formatting and Localizing Numbers:
The ZO_LocalizeDecimalNumber function in libraries/globals/localization.lua provides this function to format numbers nicely for humans.

Usage is simple: call this function on your number, and then pass the result through the `zo_strformat` function to localize it. If you do not, you will use English localization even in foreign languages.

```lua
zo_strformat("<<1>>", ZO_LocalizeDecimalNumber(1000000))
-- in English: 1,000,000
-- in German: 1.000.000
```

This also correctly handles decimals:
```lua
zo_strformat("<<1>>", ZO_LocalizeDecimalNumber(1000.987))
-- in English: 1,000.987
-- in German: 1.000,987
```

You should always use this method to format numbers that people will read.

Additional number formatting functions, which abbreviate the value (e.g. 10000 => 10k) are:
- `ZO_AbbreviateNumber(amount, precision, useUppercaseSuffixes)`
- `ZO_AbbreviateAndLocalizeNumber(amount, precision, useUppercaseSuffixes)`

]]

--- Formats a string using the provided arguments.
---
--- The syntax `<<n>>` is used as placeholder for the replacement value, where the number `n` is the position of the argument, with a maximum of 7 positional arguments.
---
--- <h2>Sentence Pluralisation</h2>
---
--- - handled with special syntax like `<<1[no examples/one example/$d examples]>>`
--- - multi layer example:
---   - `<<1[no <<m:2>>/one <<2>>/$d <<m:2>>]>>`
---   - `fun(expr, 0, "Dungeon^n")` => `no Dungeons`
---   - `fun(expr, 1, "Dungeon^n")` => `one Dungeon`
---   - `fun(expr, 9, "Dungeon^n")` => `9 Dungeons`
---
---<h2>Control Characters</h2>
---
--- Control characters added to the end of a string can determine the transormations performed with format modifiers.
---
--- - unique words, people or places (big letters)
---   - `^F` : feminine name (`Ayrenn^F`)
---   - `^M` : masculine name (`Jorunn^M`)
---   - `^N` : neuter name (`Nchuleft^N`)
---   - `^P` : plural name (`Faroe^P`) - "the Faroe (islands)"
--- - common nouns (small letters)
---   - `^f` : feminine gender (`Wand^f` => `die Wand`) - "the wall"
---   - `^m` : masculine gender (`Boden^m` => `der Boden`) -"the floor"
---   - `^n` : neuter gender (`Dach^n` => `das Dach`) - "the roof"
---   - `^p` : plural
--- - other modifiers
---   - `^c` : capitalise the word before the noun (`endloses Archiv^nc` => `Endloses Archiv`)
---   - `^d` : forces definitive article for unique names???
---     - `Archiv^nd` => `das Archiv`
---     - `Archiv^n` => `Archiv`
---   - `^f:m`: supply separate modifiers for colon separated words (formatting converts colon expressions into a sentence structure)
---     - `Blaupause: Tisch^fd:m` => `die Blaupause für einen Tisch` - "the blueprint for a table"
---
--- Formatting adds articles, when handling lowercase gender in English! Use uppercase genders like `name^P` in the translations for any languages, that need to avoid those articles:
--- - `<<l:1>> guards^p,from` => `from the guards`
--- - `<<l:1>> guards^P,from` => `from guards`
---
---<h1>Format Modifiers</h1>
---
--- Can be used in two forms: `<<Z:1>>` or `<<1{Z}>>`
---
--- <h2>Articles</h2>
---
--- - `a` : indefinite article ("a/an")
---   - `<<a:1>> Dungeon^n,in` => `ein Dungeon`
---   - `m` adds "some" quantifier
---   - `l` adds "at/in/on" propositions for locations
--- - `A`: definite article
---   - `"<<IA:1>>", "Dungeon^n,in"` => `im Dungeon` ("in the dungeon")
---
--- <h2>Locations</h2>
---
--- - `l` : location propositions ("in the/on the/..")
---   - `<<l:1>> Dungeon^n,in` => `im Dungeon` ("in the dungeon")
--- - `L` : location propositions ("to the/..")
---   - `<<L:1>> Dungeon^n,in` => `in das Dungeon` ("into the dungeon")
---
--- <h2>Pronouns</h2>
---
--- - `d` : demonstrative pronoun ("this/these/...")
---   - `<<d:1>> Dungeon^n,in` => `dieses Dungeon`
--- - `D` : just the pronoun ("this/these/...")
---   - `<<D:1>> Dungeon^n,in` => `dieses` ("this")
--- - `g` : append possessive form ("'s"/"'") or "of a"
---   - `<<g:1>> Dungeon^n,in` => `eines Dungeons` ("of a dungeon")
--- - `G` : append possessive form ("'s"/"") or "of the"
---   - `<<G:1>> Dungeon^n,in` => `des Dungeons` ("of the dungeon")
--- - `p` : personal pronoun ("he/she/it")
---   - `<<p:1>> Wand^f,auf` => `sie`
---   - `<<p:1>> Boden^m,auf` => `er`
---   - `<<p:1>> Dungeon^n,in` => `es`
--- - `P` : personal pronoun ("him/her/it")
---   - `<<P:1>> Wand^f,auf` => `ihr` ("her")
---   - `<<P:1>> Boden^m,auf` => `ihm` ("him")
---   - `<<P:1>> Dungeon^n,in` => `ihm` ("it")
--- - `r` : reflexive ("himself","herself","itself")
---   - `<<r:1>> Dungeon^n` => `sich` ("itself")
--- - `o` : possessive pronoun subject ("his","her","its") - NOT IMPLEMENTED?
--- - `O` : possessive pronoun object ("his","hers","its") - NOT IMPLEMENTED?
---
--- <h2>Formatting</h2>
---
--- - `c` : `ABC DE F` => `aBC DE F` (lowercase first letter)
--- - `C` : `abc de f` => `Abc de f` (uppercase first letter)
--- - `t` : `abc de f` => `Abc De f` (uppercase 1st each word)
--- - `T` : `abc de f` => `Abc De F` (uppearcase 1st each string)
--- - `n` : `3` => `three` (number to text)
--- - `N` : `3` => `Three` (number to text, capitalised)
--- - `i`/`I` : `1` => `1st` (number to ordinal)
--- - `R` : `12` => `XII` (number to roman)
--- - `X` : `Dungeon^n,in` => `Dungeon^n,in` (no formatting)
--- - `z` : `AÖÄẞ` => `aöäß` (to lowercase)
--- - `Z` : `aöäß` => `AÖÄẞ` (to uppercase)
---
--- <h2>Multiples</h2>
---
--- - `m` : pluralises a word
---   - `<<m:1>> Dungeon^n,in` => `Dungeons`
---
--- <h2>Combinations</h2>
---
--- All modifiers can be combined, for example. Incompatible ones are ignored.
--- - `<<al:1>> Dungeon^n,in` => `in einem Dungeon` ("in a dungeon")
--- - `<<m:1>> Dungeon^n,in` => `Dungeons`
--- - `<<ml:1>> Dungeon^n,in` => `in den Dungeons` ("in the dungeons")
--- - `<<mL:1>> Dungeon^n,in` => `in die Dungeons` ("into the dungeons")
--- - `<<ma:1>> Dungeon^n,in` => `einige Dungeons` ("some dungeons")
---
---@param format string The format of the string like "Hello <<1>>"

---@param arg1 string|number positional arg
---@param arg2? string|number positional arg
---@param arg3? string|number positional arg
---@param arg4? string|number positional arg
---@param arg5? string|number positional arg
---@param arg6? string|number positional arg
---@param arg7? string|number positional arg

---@return string formatted result
---@see esoui [ESOUI-Documentation](https://wiki.esoui.com/How_to_format_strings_with_zo_strformat)
function zo_strformat(format, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
  return ""
end

---table.concat but with custom separator as first argument
---@param separator string glue
---@param ... string items
---@return string
function zo_strjoin(separator, ...)
  return ""
end

--- @alias CurrencyType : number
---| 0 # CURT_NONE (No currency)
---| 1 # CURT_MONEY (Gold)
---| 2 # CURT_ALLIANCE_POINTS (AP)
---| 3 # CURT_TELVAR_STONES (TelVar)
---| 4 # CURT_WRIT_VOUCHERS (Writ Vouchers)
---| 5 # CURT_CHAOTIC_CREATIA (Transmutation Crystal)
---| 6 # CURT_CROWN_GEMS (Crown Gems)
---| 7 # CURT_CROWNS (Crowns)
---| 8 # CURT_STYLE_STONES (Style Mimic Stones)
---| 9 # CURT_EVENT_TICKETS (Event Tickets)
---| 10 # CURT_UNDAUNTED_KEYS (Undaunted Keys)
---| 11 # CURT_ENDEAVOR_SEALS (Seals of Endeavor)
---| 12 # CURT_ARCHIVAL_FORTUNES (Infinite Archive)

---@type CurrencyType
CURT_NONE = 0
---@type CurrencyType
CURT_MONEY = 1
---@type CurrencyType
CURT_ALLIANCE_POINTS = 2
---@type CurrencyType
CURT_TELVAR_STONES = 3
---@type CurrencyType
CURT_WRIT_VOUCHERS = 4
---@type CurrencyType
CURT_CHAOTIC_CREATIA = 5
---@type CurrencyType
CURT_CROWN_GEMS = 6
---@type CurrencyType
CURT_CROWNS = 7
---@type CurrencyType
CURT_STYLE_STONES = 8
---@type CurrencyType
CURT_EVENT_TICKETS = 9
---@type CurrencyType
CURT_UNDAUNTED_KEYS = 10
---@type CurrencyType
CURT_ENDEAVOR_SEALS = 11
---@type CurrencyType
---@deprecated Use CURT_ARCHIVAL_FORTUNES
CURT_ENDLESS_DUNGEON = 12
---@type CurrencyType
CURT_ARCHIVAL_FORTUNES = 12

---@alias FormatType : number
---| 1 # ZO_CURRENCY_FORMAT_AMOUNT_NAME
---| 2 # ZO_CURRENCY_FORMAT_WHITE_AMOUNT_WHITE_NAME
---| 3 # ZO_CURRENCY_FORMAT_PARENTHETICAL_AMOUNT
---| 4 # ZO_CURRENCY_FORMAT_AMOUNT_ICON
---| 5 # ZO_CURRENCY_FORMAT_WHITE_AMOUNT_ICON
---| 6 # ZO_CURRENCY_FORMAT_ERROR_AMOUNT_ICON
---| 7 # ZO_CURRENCY_FORMAT_PLURAL_NAME_ICON
---| 8 # ZO_CURRENCY_FORMAT_STRIKETHROUGH_AMOUNT_ICON

---@type FormatType
ZO_CURRENCY_FORMAT_AMOUNT_NAME = 1
---@type FormatType
ZO_CURRENCY_FORMAT_WHITE_AMOUNT_WHITE_NAME = 2
---@type FormatType
ZO_CURRENCY_FORMAT_PARENTHETICAL_AMOUNT = 3
---@type FormatType
ZO_CURRENCY_FORMAT_AMOUNT_ICON = 4
---@type FormatType
ZO_CURRENCY_FORMAT_WHITE_AMOUNT_ICON = 5
---@type FormatType
ZO_CURRENCY_FORMAT_ERROR_AMOUNT_ICON = 6
---@type FormatType
ZO_CURRENCY_FORMAT_PLURAL_NAME_ICON = 7
---@type FormatType
ZO_CURRENCY_FORMAT_STRIKETHROUGH_AMOUNT_ICON = 8

---Format currency string for PC/Keyboard
---<br>Example:
---<br>    ZO_Currency_FormatKeyboard(CURT_TELVAR_STONES, 12345, ZO_CURRENCY_FORMAT_PLURAL_NAME_ICON)
---<br> --> "12,345 Tel Var Stones [ICON]"
---@param currencyType CurrencyType
---@param currencyAmount integer like 12345
---@param formatType FormatType like ZO_CURRENCY_FORMAT_PLURAL_NAME_ICON
---@param extraOptions table|nil {showCap, currencyLocation, color, iconInheritColor}
---@return string
function ZO_Currency_FormatKeyboard(currencyType, currencyAmount, formatType, extraOptions)
  return ""
end

--- @param zoneId integer
--- @return string names
function GetZoneNameById(zoneId)
  return ""
end

--- @param stringVariablePrefix string
--- @param contextId integer
--- @overload fun(contextId: integer|string): string
--- @return string
function GetString(stringVariablePrefix, contextId)
  return ""
end

--- @param skillLineId integer
--- @return string name
function GetSkillLineNameById(skillLineId)
  return ""
end

---@class MonsterSocialClass : number

---@type MonsterSocialClass Alchemist
SI_MONSTERSOCIALCLASS2 = 1021
---@type MonsterSocialClass Artisan
SI_MONSTERSOCIALCLASS3 = 1022
---@type MonsterSocialClass Assassin
SI_MONSTERSOCIALCLASS4 = 1023
---@type MonsterSocialClass Bard
SI_MONSTERSOCIALCLASS5 = 1024
---@type MonsterSocialClass Beggar
SI_MONSTERSOCIALCLASS6 = 1025
---@type MonsterSocialClass Chef
SI_MONSTERSOCIALCLASS7 = 1026
---@type MonsterSocialClass Civil Servant
SI_MONSTERSOCIALCLASS8 = 1027
---@type MonsterSocialClass Clothier
SI_MONSTERSOCIALCLASS9 = 1028
---@type MonsterSocialClass Commoner
SI_MONSTERSOCIALCLASS10 = 1029
---@type MonsterSocialClass Crafter
SI_MONSTERSOCIALCLASS11 = 1030
---@type MonsterSocialClass Cultist
SI_MONSTERSOCIALCLASS12 = 1031
---@type MonsterSocialClass Drunkard
SI_MONSTERSOCIALCLASS13 = 1032
---@type MonsterSocialClass Farmer
SI_MONSTERSOCIALCLASS14 = 1033
---@type MonsterSocialClass Fighter
SI_MONSTERSOCIALCLASS15 = 1034
---@type MonsterSocialClass Fisher
SI_MONSTERSOCIALCLASS16 = 1035
---@type MonsterSocialClass Gatherer
SI_MONSTERSOCIALCLASS17 = 1036
---@type MonsterSocialClass Ghost
SI_MONSTERSOCIALCLASS18 = 1037
---@type MonsterSocialClass Guard
SI_MONSTERSOCIALCLASS19 = 1038
---@type MonsterSocialClass Healer
SI_MONSTERSOCIALCLASS20 = 1039
---@type MonsterSocialClass Hunter
SI_MONSTERSOCIALCLASS21 = 1040
---@type MonsterSocialClass Laborer
SI_MONSTERSOCIALCLASS22 = 1041
---@type MonsterSocialClass Mage
SI_MONSTERSOCIALCLASS23 = 1042
---@type MonsterSocialClass Merchant
SI_MONSTERSOCIALCLASS24 = 1043
---@type MonsterSocialClass Noble
SI_MONSTERSOCIALCLASS25 = 1044
---@type MonsterSocialClass Nude
SI_MONSTERSOCIALCLASS26 = 1045
---@type MonsterSocialClass Ordinator
SI_MONSTERSOCIALCLASS27 = 1046
---@type MonsterSocialClass Outlaw
SI_MONSTERSOCIALCLASS28 = 1047
---@type MonsterSocialClass Pilgrim
SI_MONSTERSOCIALCLASS29 = 1048
---@type MonsterSocialClass Priest
SI_MONSTERSOCIALCLASS30 = 1049
---@type MonsterSocialClass Prisoner
SI_MONSTERSOCIALCLASS31 = 1050
---@type MonsterSocialClass Provisioner
SI_MONSTERSOCIALCLASS32 = 1051
---@type MonsterSocialClass Sailor
SI_MONSTERSOCIALCLASS33 = 1052
---@type MonsterSocialClass Scholar
SI_MONSTERSOCIALCLASS34 = 1053
---@type MonsterSocialClass Servant
SI_MONSTERSOCIALCLASS35 = 1054
---@type MonsterSocialClass Skeleton
SI_MONSTERSOCIALCLASS36 = 1055
---@type MonsterSocialClass Slave
SI_MONSTERSOCIALCLASS37 = 1056
---@type MonsterSocialClass Smith
SI_MONSTERSOCIALCLASS38 = 1057
---@type MonsterSocialClass Soldier
SI_MONSTERSOCIALCLASS39 = 1058
---@type MonsterSocialClass Student
SI_MONSTERSOCIALCLASS40 = 1059
---@type MonsterSocialClass Thief
SI_MONSTERSOCIALCLASS41 = 1060
---@type MonsterSocialClass Vampire
SI_MONSTERSOCIALCLASS42 = 1061
---@type MonsterSocialClass Warrior
SI_MONSTERSOCIALCLASS43 = 1062
---@type MonsterSocialClass Watchmen
SI_MONSTERSOCIALCLASS44 = 1063
---@type MonsterSocialClass Werewolf
SI_MONSTERSOCIALCLASS45 = 1064
---@type MonsterSocialClass Woodwoker
SI_MONSTERSOCIALCLASS46 = 1065
---@type MonsterSocialClass Daedra
SI_MONSTERSOCIALCLASS47 = 1066

-- ////// END   : Manual entries and overrides

-- ////// START : GENERATED FROM LibFurnitureCatalogue/locale/en.lua
SI_FURC_DATAMINED_UNCLEAR = "This item has been seen in-game, but it's not yet known where you can get it."
SI_FURC_DB = "The Dark Brotherhood supplies vendor hands these out "
SI_FURC_DB_EQUIP = "with equipment"
SI_FURC_DB_POISON = "with poison"
SI_FURC_DB_STEALTH = "as a way to be less obtrusive"
SI_FURC_EVENT = "event"
SI_FURC_EVENT_ANNIVERSARY = "Anniversary Jubilee"
SI_FURC_EVENT_BLACKWOOD = "Bounties of Blackwood"
SI_FURC_EVENT_CRIME = "Crime Wave"
SI_FURC_EVENT_ELSWEYR = "Season of the Dragon"
SI_FURC_EVENT_HEARTS = "Hearts Week"
SI_FURC_EVENT_HOLLOWJACK = "Sinister Hollowjack"
SI_FURC_EVENT_IC = "Imperial City Celebration 2020"
SI_FURC_EVENT_JESTER = "Jester's Festival"
SI_FURC_EVENT_MAYHEM = "Whitestrake's Mayhem"
SI_FURC_EVENT_NEWLIFE = "New Life Festival"
SI_FURC_EVENT_NIGHTMARKET = "Night Market"
SI_FURC_EVENT_ORSINIUM = "Orsinium Celebration 2019"
SI_FURC_EVENT_UNDAUNTED = "Undaunted Celebration"
SI_FURC_EVENT_WITCHES = "Witches Festival"
SI_FURC_EVENT_WRITHING = "Writhing Wall"
SI_FURC_EVENT_ZENITHAR = "Zeal of Zenithar"
SI_FURC_GRAMMAR_CONJ_OR = "or"
SI_FURC_GRAMMAR_PREP_LOC_DEFAULT = "in"
SI_FURC_GRAMMAR_PREP_SRC_DEFAULT = "from"
SI_FURC_GUILD_FIGHTERS = "the Fighters' guild"
SI_FURC_GUILD_FIGHTERS_STEWARD = "Hall Steward"
SI_FURC_GUILD_MAGES = "the Mages' guild"
SI_FURC_GUILD_MAGES_MYSTIC = "Mystic^n"
SI_FURC_GUILD_PSIJIC_NALIRSEWEN = "Nalirsewen"
SI_FURC_GUILD_THIEVES_MERCH = "Outlaw Refuge, Merchant"
SI_FURC_GUILD_UNDAUNTED_QM = "Quartermaster"
SI_FURC_HOUSE = "Included in: <<1>>"
SI_FURC_HOUSE_MORE = "<<1>> and <<2>> more"
SI_FURC_ITEMPACK_DWEMER = "Dwemer"
SI_FURC_ITEMPACK_EBONY = "Ebony Blade Style"
SI_FURC_ITEMPACK_FIRSTBLADE = "Firstblade Style"
SI_FURC_ITEMPACK_JYGGALAG = "Sword of Jyggalag Style"
SI_FURC_ITEMPACK_RAZOR = "Mehrunes' Razor"
SI_FURC_ITEMPACK_STABLE = "Steadfast Stablemaster Bundle"
SI_FURC_LOC_ANY = "anywhere^X"
SI_FURC_LOC_ANY_CAPITAL = "any capital city"
SI_FURC_LOC_ANY_CITY = "any city"
SI_FURC_LOC_LILANDRIL = "Lilandril"
SI_FURC_LOC_MURKMIRE_LIL = "Lilmoth"
SI_FURC_LOC_PLACE_ORSINIUM = "Orsinium"
SI_FURC_LOC_REACH_MARKARTH_MM = "Markarth Mercantile"
SI_FURC_LOC_SELSWEYR_DHA = "Dragonhold Armoury"
SI_FURC_LOC_SELSWEYR_SENCHAL_MARKET = "Senchal, Marketplace"
SI_FURC_LOC_SHADOWFEN_CORIMONT = "Alten Corimont"
SI_FURC_LOC_STONEFALLS_EBONHEART = "Ebonheart"
SI_FURC_LOC_STORMHAVEN_WAY_MERCH = "Stormhaven, Wayrest, Merchant district"
SI_FURC_LOC_SUMMERSET_ALINOR = "Alinor"
SI_FURC_LOC_SUMMERSET_ALINOR_RIVERSIDE = "Riverside Market"
SI_FURC_LOC_UNDAUNTED = "Undaunted Enclaves^p,in"
SI_FURC_LOC_VVARDENFELL_ALDRUHN = "Ald'ruhn"
SI_FURC_LOC_VVARDENFELL_SURAN = "Suran"
SI_FURC_LOC_VVARDENFELL_VIVEC = "Vivec City"
SI_FURC_LOC_VVARDENFELL_VIVEC_GQ = "Gladiator's Quarters"
SI_FURC_LOC_VVARDENFELL_VIVEC_SDI = "Saint Delyn Inn"
SI_FURC_LOC_WSKYRIM_SOLI_DH = "Solitude, Dragon's Hearth"
SI_FURC_NPC_AUTOMATON = "automaton^n"
SI_FURC_PART_OF = "Part of item <<1>>"
SI_FURC_RANK = "rank <<1>>"
SI_FURC_RARITY_EXTREMELYRARE = "extremely rare"
SI_FURC_RARITY_RARE = "rare"
SI_FURC_REQUIRES_ACHIEVEMENT = "requires <<1>>"
SI_FURC_REWARD_RANKED_MAIL = "ranked, in mailbox"
SI_FURC_RUINS = "ruins^p"
SI_FURC_SRC_BAZAAR = "Gold Coast Bazaar"
SI_FURC_SRC_CHESTS = "treasure chests^P,from"
SI_FURC_SRC_CLAM_GIANT = "giant clams^p,from"
SI_FURC_SRC_COLLECTIBLE = "Collectible"
SI_FURC_SRC_CRAFTING = "crafting^N,by"
SI_FURC_SRC_DOLMEN = "Dolmen^P,from"
SI_FURC_SRC_DROP = "drop^n,from"
SI_FURC_SRC_DUNG = "dungeon^n,from"
SI_FURC_SRC_EDITOR = "Housing Editor"
SI_FURC_SRC_EDITOR_TAG = "<<1>> (<<2>>)"
SI_FURC_SRC_EMPTY =
  "Item source unknown.\nTry to re-scan files (refresh button right click).\nIf the item is still unknown - and not part of the weekend furnisher's current inventory - please send a mail with the item link and -source to @WolfStar07."
SI_FURC_SRC_FISH = "fishing^N,by"
SI_FURC_SRC_GEYSER = "geysers^p,from"
SI_FURC_SRC_HARVEST = "harvesting^N,from"
SI_FURC_SRC_ITEMBUNDLE = "Crown Store bundle: <<1>>"
SI_FURC_SRC_ITEMPACK = "Part of <<1>>"
SI_FURC_SRC_LVLUP = "levelup reward^n,from"
SI_FURC_SRC_MISCHOUSE = "From select house purchases"
SI_FURC_SRC_PICK = "pickpocketing^N,from"
SI_FURC_SRC_QUEST = "quest^n,from"
SI_FURC_SRC_QUEST_DAILY = "daily quests^p,from"
SI_FURC_SRC_RNDMOB = "random mobs^p,from"
SI_FURC_SRC_RUMOUR_ITEM = "This item has been datamined, but not seen in-game"
SI_FURC_SRC_RUMOUR_RECIPE = "This recipe has been datamined, but not seen in-game"
SI_FURC_SRC_SAFEBOX = "safeboxes^P,from"
SI_FURC_SRC_SCAMBOX = "Crown Crate^n,from"
SI_FURC_SRC_SCRYING = "scrying^N,from"
SI_FURC_SRC_STEAL = "stealing^N,from"
SI_FURC_SRC_TOMESPACK = "Part of the Tamriel Tomes item pack [<<1>>] "
SI_FURC_SRC_TOT = "Tales of Tribute^P,from"
SI_FURC_STRING_PIECES = "<<1>> pieces"
SI_FURC_STRING_REWARD_FOR = "reward for <<1>>"
SI_FURC_STRING_WEEKEND_AROUND = "around <<1>>"
SI_FURC_TELVANNI_NECROM_FRF = "Necrom, Final Rest Furnishings"
SI_FURC_TOMBS = "tombs^p"
SI_FURC_TOMESPACK_ARMOR = "Armor Principles"
SI_FURC_TOMESPACK_DAWN = "Dawn and Dusk"
SI_FURC_TOMESPACK_LOGIC = "Study of Wisdom and Logic"
SI_FURC_TRADERS_AF = "Achievement Furnisher^n,from"
SI_FURC_TRADERS_ALCHEMISTS = "alchemists"
SI_FURC_TRADERS_BGF = "Battlegrounds Furnishers^p,from"
SI_FURC_TRADERS_BLACKSMITHS = "blacksmiths"
SI_FURC_TRADERS_CAF = "Capital Achievement Furnisher^n,from"
SI_FURC_TRADERS_CARPENTERS = "carpenters"
SI_FURC_TRADERS_CLOTHIERS = "clothiers"
SI_FURC_TRADERS_COLL_MERCH = "Collectibles Merchant"
SI_FURC_TRADERS_COOKS = "cooks"
SI_FURC_TRADERS_ENCHANTERS = "enchanters"
SI_FURC_TRADERS_EVENT = "Impressario^Nd,from"
SI_FURC_TRADERS_FAUSTINA = "Faustina Curio"
SI_FURC_TRADERS_HGF = "Home Goods Furnisher^n,from"
SI_FURC_TRADERS_HOLIDAY = "Holiday Furnisher^n,from"
SI_FURC_TRADERS_LUXF = "Luxury Furnisher^Nd,from"
SI_FURC_TRADERS_NM = "Night Market Vendors^n,from"
SI_FURC_TRADERS_ROLIS = "Rolis Hlaalu"
-- ////// END   : GENERATED FROM LibFurnitureCatalogue/locale/en.lua
